services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  kafka:
    image: docker.redpanda.com/vectorized/redpanda:v21.11.15
    ports:
      - '8081:8081'
      - '8082:8082'
      - '9092:9092'
      - '28082:28082'
      - '29092:29092'
    command:
      - redpanda
      - start
      - '--smp'
      - '1'
      - '--reserve-memory'
      - 0M
      - '--overprovisioned'
      - '--node-id'
      - '0'
      - '--kafka-addr'
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - '--advertise-kafka-addr'
      - PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
      - '--pandaproxy-addr'
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - '--advertise-pandaproxy-addr'
      - PLAINTEXT://kafka:28082,OUTSIDE://localhost:8082
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - '9002:8080'
    environment:
      KAFKA_BROKERS: kafka:29092
    depends_on:
      - kafka
